# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.leftwing20] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftwing20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.leftwing21] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftwing21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.leftwing22] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftwing22 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.leftwing23] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftwing23 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.leftwing1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftwing1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.leftwing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftwing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rightwing20] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightwing20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rightwing21] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightwing21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rightwing22] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightwing22 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rightwing23] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightwing23 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rightwing1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightwing1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rightwing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightwing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.neck4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.neck3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.neck2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.neck1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.neck0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.frontlegl] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frontlegl set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.frontlegtipleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frontlegtipleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.frontfootleftd] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frontfootleftd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.frontfootleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frontfootleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.frontlegr] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frontlegr set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.frontlegtipright] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frontlegtipright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.frontfootrightd] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frontfootrightd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.frontfootright] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frontfootright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rearlegl] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rearlegl set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rearfootleftd] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rearfootleftd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rearfootleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rearfootleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rearlegtipleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rearlegtipleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rearlegr] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rearlegr set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rearfootrightd] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rearfootrightd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rearfootright] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rearfootright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.rearlegtipright] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rearlegtipright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail11] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.tail0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out