# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dragonmounts.root] run return 0
execute on passengers if entity @s[tag=aj.dragonmounts.data] unless data entity @s {data:{rigHash: '602813cf8502ab08e1f949cbfdf00c2598c26c7804365b8faee2bdfc3ac34db8'}} on vehicle run function animated_java:dragonmounts/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1