# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dragonmounts.root] run return 0
execute on passengers if entity @s[tag=aj.dragonmounts.data] unless data entity @s {data:{rigHash: '0164fdaad2c6f8f0fc181526600ad30bd93a6ace47f129e18ecc0d16c8e250bd'}} on vehicle run function animated_java:dragonmounts/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1