# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dragonmounts.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.dragonmounts.animation.idle.playing] run function animated_java:dragonmounts/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.dragonmounts.animation.walk.playing] run function animated_java:dragonmounts/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.dragonmounts.animation.sit.playing] run function animated_java:dragonmounts/animations/sit/zzz/on_tick
execute if entity @s[tag=aj.dragonmounts.animation.baby.playing] run function animated_java:dragonmounts/animations/baby/zzz/on_tick
execute if entity @s[tag=aj.dragonmounts.animation.fly.playing] run function animated_java:dragonmounts/animations/fly/zzz/on_tick
execute if entity @s[tag=aj.dragonmounts.animation.hover.playing] run function animated_java:dragonmounts/animations/hover/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function animated_java:dragonmounts/ai/tick