# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dragonmounts.root] run return 0
execute on passengers if entity @s[tag=aj.dragonmounts.data] unless data entity @s {data:{rigHash: 'c300ad151cc698969ac49ef2735682411fec7594e3fb35343a9dbe878eeda2f3'}} on vehicle run function animated_java:dragonmounts/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1