# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dragonmounts.root] run return 0
execute on passengers if entity @s[tag=aj.dragonmounts.data] unless data entity @s {data:{rigHash: '7877f04f26562fff1c451c908b25ef617af86840d8c50e928b0dc5b8e7eaecb5'}} on vehicle run function animated_java:dragonmounts/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1