# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:dragonmounts/animations/baby/zzz/apply_frame {frame: 55}
scoreboard players add @s aj.baby.frame 1