# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:dragonmounts/animations/fly/zzz/apply_frame {frame: 28}
scoreboard players add @s aj.fly.frame 1