# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.leftwing20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leftwing20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.leftwing21] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leftwing21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.leftwing22] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leftwing22 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.leftwing23] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leftwing23 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.leftwing1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leftwing1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.leftwing] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leftwing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rightwing20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rightwing20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rightwing21] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rightwing21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rightwing22] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rightwing22 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rightwing23] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rightwing23 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rightwing1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rightwing1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rightwing] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rightwing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.eyebrow] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyebrow set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.neck4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.neck3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.neck2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.neck1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.neck0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.frontlegl] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontlegl set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.frontlegtipleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontlegtipleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.frontfootleftd] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontfootleftd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.frontfootleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontfootleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.frontlegr] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontlegr set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.frontlegtipright] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontlegtipright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.frontfootrightd] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontfootrightd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.frontfootright] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_frontfootright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rearlegl] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rearlegl set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rearfootleftd] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rearfootleftd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rearfootleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rearfootleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rearlegtipleft] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rearlegtipleft set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rearlegr] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rearlegr set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rearfootrightd] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rearfootrightd set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rearfootright] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rearfootright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.rearlegtipright] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rearlegtipright set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.tail0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.saddle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_saddle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dragonmounts.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out