# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:dragonmounts/zzz/summon/as_data_entity
execute if data storage aj:temp args.variant run function animated_java:dragonmounts/zzz/summon/variant_arg/process with storage aj:temp args
function animated_java:dragonmounts/set_default_pose
execute if data storage aj:temp args.animation run function animated_java:dragonmounts/zzz/summon/animation_arg/process with storage aj:temp args
tp @s ~ ~ ~ ~ ~
execute at @s on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 3
execute on passengers run data modify entity @s teleport_duration set value 3
execute if entity @s[tag=!aj.dragonmounts.animation.baby.playing] run function animated_java:dragonmounts/ai/spawn_adult
execute if entity @s[tag=aj.dragonmounts.animation.baby.playing] run function animated_java:dragonmounts/ai/baby_phase/spawn_baby
tag @s remove aj.new
execute on passengers run tag @s remove aj.new